---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */
# Load the jobs from split files
include:
- project: 'julkiset-sivut/gitlab'
  ref: 'master'
  file:
  - '/workflow-mr.yml'
  - '/docker.yml'
  - '/trivy.yml'

stages:
- 'lint'
- 'build'
- 'scan'
- 'push'
- 'deploy'

variables:
  # Image names
  RENDERTRON_IMAGE: 'quay.io/tike/helsinki-fi-rendertron'
  RENDERTRON_BUILD_IMAGE: 'quay.io/tike/helsinki-fi-rendertron:build-${CI_PIPELINE_ID}'
  RENDERTRON_TARBALL: 'rendertron'

build:rendertron:
  extends: '.docker-build'
  variables:
    BUILD_IMAGE: '${RENDERTRON_BUILD_IMAGE}'
    BUILD_DIR: 'rendertron'
    DOCKERFILE: 'rendertron/Dockerfile'
    TARBALL: '${RENDERTRON_TARBALL}'

scan:trivy:rendertron:
  needs:
  - 'build:rendertron'

  extends: '.trivy'
  variables:
    TRIVY_INPUT: '${RENDERTRON_TARBALL}.tar'
