---
## /* vim: set ft=yaml tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

all:
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  hosts:
    render-22.it.helsinki.fi:
      prerender_hostname: "render.helsinki.fi"

  children:
    secrets:
      hosts:
        render-22.it.helsinki.fi:
          acme_email: "web-root@helsinki.fi"

    docker:
      hosts:
        render-22.it.helsinki.fi: {}

    prerender:
      hosts:
        render-22.it.helsinki.fi: {}

    rendertron:
      hosts:
        render-22.it.helsinki.fi: {}
