---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

collections:
- name: "ansible.posix"
- name: "community.general"
- name: "community.docker"

roles:
- src: "geerlingguy.docker"
- src: "geerlingguy.pip"
