---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: "Create the Watchtower container"
  docker_container:
    container_default_behavior: "no_defaults"
    name: "watchtower"
    image: "containrrr/watchtower"
    pull: true
    detach: true
    restart_policy: "always"
    state: "started"
    volumes:
    - "/run/docker.sock:/var/run/docker.sock"
    network_mode: "default"
    labels:
      traefik.enable: "false"
